<?php


 function autoload_267205175336d92d1686d59b4534dec5($class)
{
    $classes = array(
        'App\Currencies\XigniteGlobalCurrencies' => __DIR__ .'/XigniteGlobalCurrencies.php',
        'App\Currencies\GetRealTimeRates' => __DIR__ .'/GetRealTimeRates.php',
        'App\Currencies\GetRealTimeRatesResponse' => __DIR__ .'/GetRealTimeRatesResponse.php',
        'App\Currencies\ArrayOfRate' => __DIR__ .'/ArrayOfRate.php',
        'App\Currencies\Rate' => __DIR__ .'/Rate.php',
        'App\Currencies\Common' => __DIR__ .'/Common.php',
        'App\Currencies\OutcomeTypes' => __DIR__ .'/OutcomeTypes.php',
        'App\Currencies\Header' => __DIR__ .'/Header.php',
        'App\Currencies\GetRealTimeRate' => __DIR__ .'/GetRealTimeRate.php',
        'App\Currencies\GetRealTimeRateResponse' => __DIR__ .'/GetRealTimeRateResponse.php',
        'App\Currencies\GetForwardRate' => __DIR__ .'/GetForwardRate.php',
        'App\Currencies\GetForwardRateResponse' => __DIR__ .'/GetForwardRateResponse.php',
        'App\Currencies\ForwardRate' => __DIR__ .'/ForwardRate.php',
        'App\Currencies\ArrayOfForwardContract' => __DIR__ .'/ArrayOfForwardContract.php',
        'App\Currencies\ForwardContract' => __DIR__ .'/ForwardContract.php',
        'App\Currencies\GetLatestHistoricalRates' => __DIR__ .'/GetLatestHistoricalRates.php',
        'App\Currencies\GetLatestHistoricalRatesResponse' => __DIR__ .'/GetLatestHistoricalRatesResponse.php',
        'App\Currencies\ArrayOfHistoricalRate' => __DIR__ .'/ArrayOfHistoricalRate.php',
        'App\Currencies\HistoricalRate' => __DIR__ .'/HistoricalRate.php',
        'App\Currencies\ListCurrencies' => __DIR__ .'/ListCurrencies.php',
        'App\Currencies\ListCurrenciesResponse' => __DIR__ .'/ListCurrenciesResponse.php',
        'App\Currencies\Currencies' => __DIR__ .'/Currencies.php',
        'App\Currencies\ArrayOfCurrency' => __DIR__ .'/ArrayOfCurrency.php',
        'App\Currencies\Currency' => __DIR__ .'/Currency.php',
        'App\Currencies\ArrayOfCountry' => __DIR__ .'/ArrayOfCountry.php',
        'App\Currencies\Country' => __DIR__ .'/Country.php',
        'App\Currencies\ListActiveCurrencies' => __DIR__ .'/ListActiveCurrencies.php',
        'App\Currencies\ListActiveCurrenciesResponse' => __DIR__ .'/ListActiveCurrenciesResponse.php',
        'App\Currencies\GetAllRealTimeRates' => __DIR__ .'/GetAllRealTimeRates.php',
        'App\Currencies\GetAllRealTimeRatesResponse' => __DIR__ .'/GetAllRealTimeRatesResponse.php',
        'App\Currencies\GetLatestCrossRate' => __DIR__ .'/GetLatestCrossRate.php',
        'App\Currencies\GetLatestCrossRateResponse' => __DIR__ .'/GetLatestCrossRateResponse.php',
        'App\Currencies\GetLatestCrossRates' => __DIR__ .'/GetLatestCrossRates.php',
        'App\Currencies\GetLatestCrossRatesResponse' => __DIR__ .'/GetLatestCrossRatesResponse.php',
        'App\Currencies\GetBestCrossRate' => __DIR__ .'/GetBestCrossRate.php',
        'App\Currencies\GetBestCrossRateResponse' => __DIR__ .'/GetBestCrossRateResponse.php',
        'App\Currencies\GetBestCrossRates' => __DIR__ .'/GetBestCrossRates.php',
        'App\Currencies\GetBestCrossRatesResponse' => __DIR__ .'/GetBestCrossRatesResponse.php',
        'App\Currencies\ConvertRealTimeValue' => __DIR__ .'/ConvertRealTimeValue.php',
        'App\Currencies\ConvertRealTimeValueResponse' => __DIR__ .'/ConvertRealTimeValueResponse.php',
        'App\Currencies\RateConversion' => __DIR__ .'/RateConversion.php',
        'App\Currencies\ConvertHistoricalValue' => __DIR__ .'/ConvertHistoricalValue.php',
        'App\Currencies\ConvertHistoricalValueResponse' => __DIR__ .'/ConvertHistoricalValueResponse.php',
        'App\Currencies\GetRealTimeRateTable' => __DIR__ .'/GetRealTimeRateTable.php',
        'App\Currencies\GetRealTimeRateTableResponse' => __DIR__ .'/GetRealTimeRateTableResponse.php',
        'App\Currencies\RateTable' => __DIR__ .'/RateTable.php',
        'App\Currencies\ArrayOfRateTableLine' => __DIR__ .'/ArrayOfRateTableLine.php',
        'App\Currencies\RateTableLine' => __DIR__ .'/RateTableLine.php',
        'App\Currencies\ArrayOfQuoteCurrencyItem' => __DIR__ .'/ArrayOfQuoteCurrencyItem.php',
        'App\Currencies\QuoteCurrencyItem' => __DIR__ .'/QuoteCurrencyItem.php',
        'App\Currencies\GetHistoricalRate' => __DIR__ .'/GetHistoricalRate.php',
        'App\Currencies\GetHistoricalRateResponse' => __DIR__ .'/GetHistoricalRateResponse.php',
        'App\Currencies\GetLatestHistoricalRate' => __DIR__ .'/GetLatestHistoricalRate.php',
        'App\Currencies\GetLatestHistoricalRateResponse' => __DIR__ .'/GetLatestHistoricalRateResponse.php',
        'App\Currencies\GetHistoricalRates' => __DIR__ .'/GetHistoricalRates.php',
        'App\Currencies\GetHistoricalRatesResponse' => __DIR__ .'/GetHistoricalRatesResponse.php',
        'App\Currencies\GetHistoricalRatesRange' => __DIR__ .'/GetHistoricalRatesRange.php',
        'App\Currencies\GetHistoricalRatesRangeResponse' => __DIR__ .'/GetHistoricalRatesRangeResponse.php',
        'App\Currencies\GetHistoricalRatesRanges' => __DIR__ .'/GetHistoricalRatesRanges.php',
        'App\Currencies\GetHistoricalRatesRangesResponse' => __DIR__ .'/GetHistoricalRatesRangesResponse.php',
        'App\Currencies\GetOfficialHistoricalRate' => __DIR__ .'/GetOfficialHistoricalRate.php',
        'App\Currencies\GetOfficialHistoricalRateResponse' => __DIR__ .'/GetOfficialHistoricalRateResponse.php',
        'App\Currencies\GetOfficialRate' => __DIR__ .'/GetOfficialRate.php',
        'App\Currencies\GetOfficialRateResponse' => __DIR__ .'/GetOfficialRateResponse.php',
        'App\Currencies\HistoricalRateBidAsk' => __DIR__ .'/HistoricalRateBidAsk.php',
        'App\Currencies\GetOfficialRates' => __DIR__ .'/GetOfficialRates.php',
        'App\Currencies\GetOfficialRatesResponse' => __DIR__ .'/GetOfficialRatesResponse.php',
        'App\Currencies\ArrayOfHistoricalRateBidAsk' => __DIR__ .'/ArrayOfHistoricalRateBidAsk.php',
        'App\Currencies\GetOfficialHistoricalRates' => __DIR__ .'/GetOfficialHistoricalRates.php',
        'App\Currencies\GetOfficialHistoricalRatesResponse' => __DIR__ .'/GetOfficialHistoricalRatesResponse.php',
        'App\Currencies\GetTick' => __DIR__ .'/GetTick.php',
        'App\Currencies\GetTickResponse' => __DIR__ .'/GetTickResponse.php',
        'App\Currencies\Tick' => __DIR__ .'/Tick.php',
        'App\Currencies\GetTicks' => __DIR__ .'/GetTicks.php',
        'App\Currencies\GetTicksResponse' => __DIR__ .'/GetTicksResponse.php',
        'App\Currencies\ArrayOfTick' => __DIR__ .'/ArrayOfTick.php',
        'App\Currencies\GetBar' => __DIR__ .'/GetBar.php',
        'App\Currencies\GetBarResponse' => __DIR__ .'/GetBarResponse.php',
        'App\Currencies\Bar' => __DIR__ .'/Bar.php',
        'App\Currencies\GetBars' => __DIR__ .'/GetBars.php',
        'App\Currencies\GetBarsResponse' => __DIR__ .'/GetBarsResponse.php',
        'App\Currencies\ArrayOfBar' => __DIR__ .'/ArrayOfBar.php',
        'App\Currencies\GetChartBars' => __DIR__ .'/GetChartBars.php',
        'App\Currencies\GetChartBarsResponse' => __DIR__ .'/GetChartBarsResponse.php',
        'App\Currencies\CurrencyChartBars' => __DIR__ .'/CurrencyChartBars.php',
        'App\Currencies\CurrencyDescription' => __DIR__ .'/CurrencyDescription.php',
        'App\Currencies\ArrayOfChartBar' => __DIR__ .'/ArrayOfChartBar.php',
        'App\Currencies\ChartBar' => __DIR__ .'/ChartBar.php',
        'App\Currencies\GetLondonHistoricalRatesRange' => __DIR__ .'/GetLondonHistoricalRatesRange.php',
        'App\Currencies\GetLondonHistoricalRatesRangeResponse' => __DIR__ .'/GetLondonHistoricalRatesRangeResponse.php',
        'App\Currencies\ListOfficialRates' => __DIR__ .'/ListOfficialRates.php',
        'App\Currencies\ListOfficialRatesResponse' => __DIR__ .'/ListOfficialRatesResponse.php',
        'App\Currencies\OfficialRates' => __DIR__ .'/OfficialRates.php',
        'App\Currencies\ArrayOfOfficialCountry' => __DIR__ .'/ArrayOfOfficialCountry.php',
        'App\Currencies\OfficialCountry' => __DIR__ .'/OfficialCountry.php',
        'App\Currencies\ArrayOfOfficialCurrency' => __DIR__ .'/ArrayOfOfficialCurrency.php',
        'App\Currencies\OfficialCurrency' => __DIR__ .'/OfficialCurrency.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_267205175336d92d1686d59b4534dec5');

// Do nothing. The rest is just leftovers from the code generation.
{
}
